# -*- coding: utf-8 -*-
"""Assignment 02_21101004_AdityaBarua.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hiCkd9EYXHTsLmNcMangTKzCSnhgivz
"""

#Task -1
var1 = int (input())
var2 = int (input())
def my_function(var1,var2):
    if var2 == 0 or var1 == 0:
        return 0
    else:
        var3 = var1/var2
        var4 = var1 // var2
        var5 = var3 - var4
        return var5 
my_function(var1,var2)

#Task-2
height = int (input("enter your height in cm:"))
weight = int (input("enter your weight in kg:"))
height2 = height / 100 
def BMI(height,weight):
    bmi = round(weight / (height2**2),1)
    print("Score is",bmi, end=".")
    if bmi < 18.5:
        print("You are Underweight")
    elif bmi >= 18.5 and bmi <= 24.9 :
        print("You are Normal.")
    elif bmi >= 25 and bmi <= 30:
        print("You are Overweight")
    else:
        print("You are Obese")
BMI(height,weight)

#Task -3
minimum = int (input("enter minimum:"))
maximum = int (input("enter maximum:"))
divisor = int (input("enter divisor:"))

def my_function(minimum,maximum,divisor):
    counter = 0
    for i in range(minimum,maximum):
       if i%divisor == 0:
           counter = counter + i
    return counter
my_function(minimum,maximum,divisor)

#Task-4
name = input("name of the burger:")
place = input("location:")

def calculate_cost(name,place = "Mohakhali"):
    tax = 0.08
    total = 0
    if name == "BBQ Chicken Cheese Burger":
        total = total + 250
    elif name == "Beef Burger":
        total = total + 170
    elif name == "Naga Drums":
        total = total + 200  
    if place == "" or place == "Mohakhali":
        total = total + 40 + (total*tax)
    elif place != "Mohakhali" :
        total = total + 60 + (total*tax)
    return total
calculate_cost(name,place)

#Task - 5
var = input("enter email address:").split("@")
var1 = input("enter new domain:")
var2 = input("enter old domain:")
def replace_domain(var,var2,var1 = "sheba.xyz" ):
    if var1 in var:
        var3 = var[0] +"@" + var[1]
        print("Unchanged: ",var3)
    elif var[1] != var1:
        var[1]  = var1
        var3 = var[0] +"@" + var[1]
        print("Changed: ",var3) 
replace_domain(var,var2,var1 = "sheba.xyz" )

#Task - 6
var = input().lower()
def my_function(var):
        counter = 0
        list1 = []
        for i in var:
            if i == "a" or i == "e" or i == "o" or i == "u":
                counter += 1
                list1.append(i)
        if counter == 0:
            print("No vowels in the name")
        else:
            for i in range(len(list1)):
                if i == len(list1)-1:
                    print(list1[i],end = ".")
                else:
                    print(list1[i],end = ",")
            print("Total number of vowels:",counter)
        
my_function(var)

#Task -7
string = input()
def my_function(string):
    string2 = ""
    for i in string:
        if i == " ":
            string2 = string2
        else:
            string2 = string2 + i
    if string2 == string2[::-1]:
        return "palindrome"
    else:
        return "Not a palindrome"
print( my_function(string))

class A:
    def __init__(self):
        self.temp = 4
        self.sum = 1
        self.y = 2
        self.y = self.temp - 2
        self.sum = self.temp + 3
        self.temp -= 2
    def methodA(self, m,  n):
        x = 0
        self.y = self.y + m + self.temp
        self.temp += 1
        x = x + 2 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        
class B(A):
    def __init__(self, b=None):
        super().__init__()
        self.x = 1
        self.sum = 2
        if b == None:
            self.y = self.temp + 3
            self.sum = 3 + self.temp + 2
            self.temp -= 1
        else:
            self.sum = b.sum
            self.x = b.x
    def methodB(self, m,  n):
        y = 0
        y = y + self.y
        self.x = y + 2 + self.temp
        self.methodA(self.x, y)
        self.sum = self.x + y + self.sum
        print(self.x, y, self.sum)

a1 = A()
b1 = B()
b2 = B(b1)
a1.methodA(1, 1)
b1.methodA(1, 2)
b2.methodB(3, 2)

lis= [3,1,5,4,6,7,8]
lent= len(lis)
range= [2, 4]
dic={}
sum=0
sum1=0
for i in range(0,lent):
    sum+= lis[i]
    dict[i]= sum
for i in range(range(0),range(1)):
    sum1+=lis[i]
print(dict)
print(sum1)

c = input("Enter your string:")
li = c.split()
for i in li:
    print(i[-1::-1],end=" ")

lis= [3,1,5,4,6,7,8]
print(len(lis))

#Task-8
n=int(input("Please enter Number of Days In a year"))
def my_function(n):
    year = int (n / 365)  
    months = int ((n % 365)/30) 
    days = int (n % 365) % 30  
    print(year,"years,", months," months,",days,"days")
my_function(n)

#Task-9
str1 = input()
def my_function(str1):
    list1 = []
    str2 = ""
    for i in range(len(str1)):
        list1.append(str1[i])
    list1[0] = list1[0].upper()
    str2 += list1[0]
    for i in range(1,len(list1)-1):
        if list1[i] == "i" and list1[i-1] == " " and list1[i+1] == " ":
            str2 += "I"
        elif list1[i] == ".":
            list1[i+2] = list1[i+2].upper()
            str2 += "."
        elif list1[i] == "!":
            list1[i+2] = list1[i+2].upper()
            str2 += "!"
        elif list1[i] == "?":
            list1[i+2] = list1[i+2].upper()
            str2 += "?"
        else:
            str2 += list1[i]
    str2 += "."
    print(str2)
my_function(str1)

class Human:
    def __init__(self):
        self.age = 0
        self.height = 0.0

h1 = Human()
h2 = Human()

class Human:
    def __init__(self):
        self.age = 0
        self.height = 0.0

h1 = Human()
h2 = Human()
h1.age = 21
h1.height = 5.5
print(h1.age)
print(h1.height)
h2.height = h1.height - 3
print(h2.height)
h2.age = h1.age
h1.age += h1.age
print(h1.age)
h2 = h1
print(h2.age)
print(h2.height)
h1.age += h1.age
h2.height += h2.height
print(h1.age)
print(h1.height)
h2.age += h2.age
h1.age = h2.age
print(h2.age)

class Student:
    def __init__(self):
        self.name = None
        self.cgpa = 0.0
s1 = Student()
s2 = Student()
s3 = None
s1.name = "Student One"
s1.cgpa = 2.3
s3 = s1
s2.name = "Student Two"
s2.cgpa = s3.cgpa + 1
s3.name = "New Student"
print(s1.name)
print(s2.name)
print(s3.name)
print(s1.cgpa)
print(s2.cgpa)
print(s3.cgpa)
s3 = s2
s1.name = "old student"
s2.name = "older student"
s3.name = "oldest student"
#s2.cgpa = s1.cgpa - s3.cgpa + 4.5
print(s1.name)
print(s2.name)
print(s3.name)
print(s1.cgpa)
print(s2.cgpa)
print(s3.cgpa)

class Ninja:
    def __init__(self):
        self.rank = 0
        self.stamina = 0.0

naruto = Ninja()
yellow_flash = Ninja()
naruto.rank = 1
naruto.stamina = 95.0
print(naruto.rank)
print(naruto.stamina)
yellow_flash.stamina = naruto.stamina - 2
print(yellow_flash.stamina)
yellow_flash.rank += (naruto.rank + 1)
print(yellow_flash.rank)
minato = yellow_flash
print(minato.rank)
print(minato.stamina)
naruto.rank = minato.rank - 1
naruto.stamina = yellow_flash.stamina + 3
print(naruto.rank)
print(naruto.stamina)
naruto.rank = -(-naruto.rank)
yellow_flash.stamina = -(-minato.stamina)
print(naruto.rank)
print(minato.stamina)